language: minimal
matrix:
  include:
  - env: ARCH=windows
  - env: ARCH=macos
  - env: ARCH=linux_x86_64
addons:
  apt:
    packages:
    - unzip
    - zip
install: skip
script: ./build.sh
deploy:
  provider: releases
  api_key:
    secure: "A9jySS8IcM59kjH/3yLNIGqgaVEvRlOxQyWo9CGuahrcuOgLAshua791r3kKqf6pJ1S7SHunHQbLYL6LUDuOnqZ/IvBDGv+F663lOjC0tMJoWywjKbp4bc5u5KnMyz3l0APSg6HWE4csbhlY7R1Tx3ex4o18jPfVogu27I5EVGNc+LsTUuZZl+gU9hJoHtCBhkk5taryxzru90NBZcNuUSeiMIAsZLsJftjJiTK5QU+GdM/SzJlgvTCzq4lTjL/OlU5Y6p0fHHvL4LXmKRXfsPXOPFT7VNlIrUO1L8NakM7KNqCJbE79S3BAX24mzt01QbWyjIENCbOy7X+W0n2VnRrnGK/qzIenOLTb5Atfe7dg6pyUtwwQYVCqVp1U7ShbLjdTf8QaT9ecf6IVQjos03W+2QA8QFOcoE1M7RdYkjwHhfpoHUz1SrIBywx0Sm7UsLjpFf2VEU3fcqqZWD1pNdMO4RTTOHhQ5uyma4b2eTHOhASSDB9KJV8p1qwAVv29NUwqmL/DVIXxM0bttZv/7YPEJOLbH/whIkjV+bMuLXCKXK5/05zlSYOVWpGQA+EvkWpNpqdchZn8t1wjVx6xk5P/OynTFOKOnTmXioF5MZeW1L/pUbseYTFYqkPNqFmsF68pVF1w41LTAKDEvuqTENPEqfKdJjb4vT+5TI33DJw="
  file:
    - output/*.tar.gz
    - output/*.zip
    - output/*.sha1
    - output/*.sha256
    - output/*.sha512
  file_glob: true
  skip_cleanup: true
  on:
    repo: xobs/ecp5-toolchain
    all_branches: true
    tags: true
branches:
  only:
    # Release tags
    - /^v\d+\.\d+/